version: '3.8'
networks:
  geoquiz-network:
    driver: bridge

services:
  geoquiz-gateway:
      image: canals/php:8.2
      container_name: gateway
      volumes:
        - ./geoquiz.gateway:/var/www
        - ./geoquiz.gateway/public:/var/www/html
      ports:
        - "50015:80"
      environment:
        - APP_ENV=local
      networks:
        - geoquiz-network

  geoquiz-auth_service:
    image: canals/php:8.2
    container_name: auth_service
    volumes:
      - ./geoquiz.auth_api:/var/www
      - ./geoquiz.auth_api/public:/var/www/html
    ports:
      - "50020:80"
    environment:
      - APP_ENV=local
    depends_on:
      - geoquiz-auth_db
    networks:
      - geoquiz-network

  geoquiz-auth_db:
    image: mariadb:latest
    container_name: auth_db
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_ROOT_PASSWORD: PierreAndreGuenego
      MYSQL_USER: root
      MYSQL_PASSWORD: PierreAndreGuenego
    ports:
      - "50019:3306"
    networks:
      - geoquiz-network

  geoquiz-api_service:
    image: canals/php:8.2
    container_name: api_service
    volumes:
      - ./geoquiz.api:/var/www
      - ./geoquiz.api/public:/var/www/html
    ports:
      - "50018:80"
    environment:
      - APP_ENV=local
    restart: always
    depends_on:
      - geoquiz-api_db
      - geoquiz-auth_service
    networks:
      - geoquiz-network

  geoquiz-api_db:
    image: mariadb:latest
    container_name: api_db
    environment:
      MYSQL_DATABASE: api_db
      MYSQL_ROOT_PASSWORD: PierreAndreGuenego
      MYSQL_USER: root
      MYSQL_PASSWORD: PierreAndreGuenego
    ports:
      - "50017:3306"
    restart: always
    networks:
      - geoquiz-network

  geoquiz-front_interface:
    image: node:20-alpine
    ports:
      - "50001:5173"
    volumes:
      - ./geoquiz.front_interface:/app
    working_dir: /app
    #installing dependencies with dev dependencies and running the run dev
    command: sh -c "npm install --include=dev && npm run dev"
    networks:
      - geoquiz-network
    environment:
      - NODE_ENV=local
    depends_on:
      - geoquiz-auth_service
      - geoquiz-api_service

  geoquiz-series_database:
    image: postgis/postgis:13-master
    volumes:
      - ./geoquiz.series/data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U directus" ]
      interval: 10s
      timeout: 5s
      retries: 5

  geoquiz-series_cache:
    image: redis:6

  geoquiz-series_directus:
    image: directus/directus:10.8.3
    ports:
      - 50010:8055
    volumes:
      - ./geoquiz.series/uploads:/directus/uploads
    depends_on:
      geoquiz-series_cache:
        condition: service_started
      geoquiz-series_database:
        condition: service_healthy
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"
      WEBSOCKETS_ENABLED: "true"

      DB_CLIENT: "pg"
      DB_HOST: "geoquiz-series_database"
      DB_PORT: "127.0.0.1:5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://geoquiz-series_cache:6379"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"

      CORS_ENABLED: "true"
      CORS_ORIGIN: "*"